feature/recycler_view
ann-kensaku/ToDoRank-Android pull request #1
Opened 2019-08-15 10:15 UTC by t-fuji109

recyclerViewを追加して文字列の一覧表示を行うところまで作成しました。
出力する文字列はmainActivityで作成しています。
実機で文字列が出力されるところまで確認しました。
よろしくお願いします。

2019-08-15 12:58 UTC, shiita0903 requested changes
いい感じに書けてると思います。
幾つかコメント残したので確認して下さい。

2019-08-15 12:58 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/Item.kt
> +}
今回はプロパティの数が一つだから意味ないけど
こういったデータを保存するためのclassにはkotlinのdata class使うと良いよ
`equals`と`hashCode`が自動で実装されて、便利なメソッドが幾つか生えてる
https://dogwood008.github.io/kotlin-web-site-ja/docs/reference/data-classes.html

2019-08-15 12:58 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +    private lateinit var viewAdapter: RecyclerView.Adapter<*>
型はスーパークラス(RecyclerView.Adapter)じゃなくて、実装したクラス(RecyclerAdapter)で書いて問題ないよ

2019-08-15 12:58 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +            layoutManager = viewManager
`LinearLayoutManager`をそのまま使うだけならxmlファイルに書くほうが良いかも
`app:layoutManager`で指定できる

2019-08-16 09:15 UTC, t-fuji109 commented
勉強になりました！ありがとうございます
data classを使ってみたいので、data classの点、その他の点についても変更しました

2019-08-16 11:34 UTC, shiita0903 requested changes

2019-08-16 11:34 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +    //var myDataset: Array<String> = Array<String>(13, {i -> i.toString()})
Gitは履歴から遡れるから、今後使わないであろうコメントアウトは削除したほうがコードの品質的が上がるよ。
上のviewManagerと一緒に消してもらえると助かります。

2019-08-16 11:34 UTC, shiita0903 commented on app/src/main/res/layout/activity_main.xml
> +
これややこしいんだけど、`ConstraintLayout`では`match_parent`使っちゃだめなんだよね。
https://qiita.com/ara_tack/items/68c07529c1477c56997f
使えるのは`wrap_content`と`~dp`のに種類だけで、`match_parent`を実現したい場合には`0dp`をセットして、`app:layout_constraintTop_toTopOf="parent"`等の制約をつけて実装する感じ。

2019-08-16 13:56 UTC, t-fuji109 commented on app/src/main/res/layout/activity_main.xml
> +
分かりました
ページを参考に変更してみます

2019-08-16 15:02 UTC, shiita0903 approved these changes
OKです．修正お疲れ様

2019-08-16 15:02 UTC, merged