feature/move_to_edit
ann-kensaku/ToDoRank-Android pull request #2
Opened 2019-08-17 23:26 UTC by t-fuji109

2.RecyclerViewのitemをタップした時に編集画面に遷移
です。
MainActivityでのsetOnItemClickListenerで、onItemClickを書かないとエラーになってしまうのが気になっています
よろしくお願いします。

2019-08-18 03:39 UTC, tks10 commented
onItemClickを書かないといけないのは、実装してるインターフェースにデフォルト実装が無いからだね〜
振る舞いをこちら側で書いてあげないとコンパイラがなにやったらいいの？ってなっちゃうから。

2019-08-18 09:58 UTC, t-fuji109 commented
コメントありがとうございます
onItemClick()での処理がinterfaceの定義内に書かれていないから、MainActivityで定義する必要がある、ということで良いですか
onItemClickはインターフェースを定義する時に定義しなくても、自動的に定義されている関数だったりするのでしょうか？RecyclerAdapter内のインターフェースの定義では定義していない関数なので不思議に思いました
理解が追いついてなくてすみません...

2019-08-18 16:16 UTC, shiita0903 requested changes
Interface利用したコールバックとかはフロントエンド開発で避けられないので、少し難しいかもしれないけど頑張って理解して下さい。

2019-08-18 16:16 UTC, shiita0903 commented on .idea/modules.xml
>      </modules>
この部分をに変更してもらえる？初期設定のミスです。すみません…
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectModuleManager">
    <modules>
      <module fileurl="file://$PROJECT_DIR$/ToDoRank-Android.iml" filepath="$PROJECT_DIR$/ToDoRank-Android.iml" />
      <module fileurl="file://$PROJECT_DIR$/app/app.iml" filepath="$PROJECT_DIR$/app/app.iml" />
    </modules>
  </component>
</project>
```

2019-08-18 16:16 UTC, shiita0903 commented on .idea/misc.xml
>      <output url="file://$PROJECT_DIR$/build/classes" />
この部分頻繁に書き換わっちゃうんだよね。元に戻してもらいたいです。
https://stackoverflow.com/questions/32878888/android-idea-misc-xmls-languagelevel-tag-keeps-changing-jdks/40083824
Use embedded JDKにチェックすれば多分勝手にJDK_1_7にならないと思うから、それで設定しておいてほしい。

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/ItemEditActivity.kt
> +        edit_text = findViewById(R.id.edit_text) as TextView
Kotlin側の変数名はスネークケースじゃなくてキャメルケースで統一しよう

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/res/layout/list_item.xml
> +    </LinearLayout>
上の方の空行の削除とこの行のインデント修正お願いします。

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/res/layout/activity_item_edit.xml
> +        android:text="Title"
Android studioのプレビュー画面で値を見たいだけなら`tools:text`を使うといいです。
この`EditText`がどんな値を入れるかをユーザに示すために`text="Title"`としているなら、`android:hint="Title"`の方が良いです。

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        holder.linearLayout.setOnClickListener({
`holder.itemView.setOnClickListener`の方が他の人にも読みやすいかな。
`itemView`は`R.layout.list_item`のルートの`View`を示しているから、`holder.linearLayout`と`holder.itemView`は同じなんだけど、`RecyclerView`のitemに対するClick処理を書くときは`itemView`使うほうが一般的。

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
>      }
リスナ渡してもいいけど、クリックした時の処理が`RecyclerAdapter`で使えればいいだけだから、コンストラクタで関数のオブジェクト渡してそれを使うと良いかも。
```kotlin
class RecyclerAdapter(
    private val toDoList: List<Item>,
    private val onClick: (Item) -> Unit  // Itemオブジェクトを受け取って何も返さない関数
)
```

MainActivity
```kotlin
viewAdapter = RecyclerAdapter(itemList) {
    // onClickの中身をここに移す
}
```

2019-08-18 16:16 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        //val binding = OriginalItemLayoutBinding.inflate(layoutInflater, parent, false)
DataBindingに挑戦しているのとても良いと思います。
後からやろうかと思ってたけど、一人で調べてできそうなら使っちゃってOKです

2019-08-18 16:26 UTC, shiita0903 commented
デフォルト実装が使われるのは結構稀で、あまり推奨されるものでは無いので今は気にしなくて大丈夫です。
基本的にはInterfaceで宣言だけして、どこかのクラス(無名クラスでもOK)で実装をするので、勝手に定義されてることはないです。

> MainActivityでのsetOnItemClickListenerで、onItemClickを書かないとエラーになってしまうのが気になっています  

具象クラスはInterfaceまたはabstractで定義されたメソッドを全て実装しなければいけないのは言語仕様です。この辺はJavaや他のOOPのプログラミング言語と同じです。


多分Kotlinの
```kotlin
object : RecyclerAdapter.OnItemClickLister {
}
```

という書き方が独特だから気づきにくかったんだと思います。
このコードはOnItemClickListerを無名クラス(正確にはシングルトンのオブジェクト)で実装しているクラス定義です。

2019-08-19 14:30 UTC, t-fuji109 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        //val binding = OriginalItemLayoutBinding.inflate(layoutInflater, parent, false)
もう少し調べてからまた挑戦してみます！

2019-08-19 14:35 UTC, tks10 commented
という感じに実際に手を動かしてるとわけわかめな所が出てくるので，それを話のタネに時々ラボに集まってミニ勉強会しても実りがありそうですね〜

2019-08-20 12:26 UTC, t-fuji109 commented
そうですね！
今回のところはイメージが分かりました
ありがとうございました

2019-08-21 16:29 UTC, shiita0903 requested changes
すみません、幾つか見落としがありました。
コメントの確認をお願いします。

2019-08-21 16:29 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/ItemEditActivity.kt
> +        editText = findViewById(R.id.edit_text) as TextView
`findViewById`はキャストじゃなくて、型引数を使って`findViewById<TextView>`って書くのが推奨されているみたい。
この例だとフィールドに型が書いてあるから型推論が効いて、'findViewById'だけで動くよ。

2019-08-21 16:29 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/ItemEditActivity.kt
> +        title = intent.getStringExtra("title") as String
このキャストはString?からStringに対するキャストで、`intent.getStringExtra("title")`がnullを返した時にNPEが起こると思う。
エルビス演算子を使って、`intent.getStringExtra("title") ?: ""`みたいに書くと堅牢なコードになります。

2019-08-21 16:29 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        })
ここはSAM変換が適用されるので
```kotin
holder.itemView.setOnClickListener { onClick(data) }
```
で大丈夫

2019-08-22 17:37 UTC, shiita0903 approved these changes

2019-08-22 17:37 UTC, merged