feature/material_dialog
ann-kensaku/ToDoRank-Android pull request #4
Opened 2019-08-29 13:30 UTC by t-fuji109

material dialogへ変更しました
前半4つのcommitは違うことをしていたため、修正しました
後半のcommitがmaterial dialogへの変更です
よろしくお願いします

2019-08-29 16:24 UTC, shiita0903 requested changes
画面の更新はDBにデータを保存できるようにするタイミングで実装が良いかと思うので、現状はこれで問題ないです。
新規追加もDialogを使うので、このタイミングで作っちゃいましょう(これに関してもDialogの表示だけでいい)。
MainActivityの右下にFloating Action Buttonを追加して、そこをタップしたら新規作成ができるようにすると良いと思います。

2019-08-29 16:24 UTC, shiita0903 commented on app/src/main/res/layout/edit_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
このファイル使ってない？

2019-08-29 16:24 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +    @SuppressLint("InflateParams")
多分必要ないと思う

2019-08-29 16:24 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +import com.afollestad.materialdialogs.input.input
Alt+Ctrl+oとかでimport文の整理ができるから、Push前にやるようにしよう

2019-08-30 02:03 UTC, t-fuji109 commented on app/src/main/res/layout/edit_dialog.xml
> +<?xml version="1.0" encoding="utf-8"?>
使ってなかったです
消します

2019-08-30 02:37 UTC, t-fuji109 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +import com.afollestad.materialdialogs.input.input
やってみます！

2019-08-31 06:40 UTC, shiita0903 requested changes
細かいですが修正をお願いします

2019-08-31 06:40 UTC, shiita0903 commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/ToDoRank-Android2.iml" filepath="$PROJECT_DIR$/ToDoRank-Android2.iml" />
これ消しといて
なんで追加されちゃうんだろ？？

2019-08-31 06:40 UTC, shiita0903 commented on app/src/main/res/layout/activity_main.xml
> +        app:srcCompat="@android:drawable/ic_input_add"
Projectウィンドウのres>drawableを右クリックnew>Vector assetからaddアイコンのxmlを追加してそれを使おう。色は白で良いかな。
あとapp:srcCompatじゃなくてandroid:srcで大丈夫だと思う。

2019-08-31 07:03 UTC, t-fuji109 commented on .idea/modules.xml
> +      <module fileurl="file://$PROJECT_DIR$/ToDoRank-Android2.iml" filepath="$PROJECT_DIR$/ToDoRank-Android2.iml" />
直しておきます
手元のファイル名に2が入っていて、そのせいだと思うので直してみました
また様子見てみます

2019-09-01 09:39 UTC, shiita0903 requested changes

2019-09-01 09:39 UTC, shiita0903 commented on app/src/main/res/layout/activity_main.xml
@t-fuji109 
`@drawable/ic_add_white_24dp`がgitで追加されていないみたい

2019-09-01 13:06 UTC, t-fuji109 commented on app/src/main/res/layout/activity_main.xml
忘れてました
ic_add_white_24dp追加しました

2019-09-01 15:07 UTC, shiita0903 approved these changes

2019-09-01 15:07 UTC, merged