feature/data_binding
ann-kensaku/ToDoRank-Android pull request #5
Opened 2019-09-02 04:10 UTC by t-fuji109

data bindingに変更してみました
よろしくお願いします

2019-09-02 06:26 UTC, shiita0903 requested changes
せっかくなのでMainActivityのfindViewByIdもDataBindingで書き換えようか

2019-09-02 06:26 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +    class RecyclerViewHolder(var binding: ListItemBinding) :
valにしよう

2019-09-02 06:26 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        val checkBox: CheckBox = binding.root.findViewById(R.id.check_box)
DataBindingしているのでfindViewByIdはやらなくてOK
この例のcheckBoxはbinding.checkBoxでアクセスできる
なのでViewHolderはbindingのインスタンスを保持するだけでOKなので、{}の中身は空でOK({}もいらない)

2019-09-02 06:26 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +        holder.binding.setData(data)
holder.binding.data = data
のようなプロパティアクセスにしよう

2019-09-02 06:26 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
>          holder.checkBox.setOnClickListener(View.OnClickListener {
上のViewHolderの修正にあわせて、holder.binding.checkBox.setOnClickListenerのようなアクセスに修正

2019-09-02 06:26 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
>              //処理を追加
Bindingの情報を即反映するためにholder.binding.executePendingBindings()が必要

2019-09-02 13:43 UTC, t-fuji109 commented
レビューありがとうございます
修正点、直してみました
よろしくお願いします

2019-09-03 08:58 UTC, shiita0903 approved these changes

2019-09-04 09:12 UTC, t-fuji109 commented
main activityのdatabindingでの書き換え行ってみました
よろしくお願いします

2019-09-04 14:15 UTC, shiita0903 requested changes

2019-09-04 14:15 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/MainActivity.kt
> +
DataBindingでsetContentViewしているので、上の方の`setContentView(R.layout.activity_main)`は必要ないから削除をお願いします。
それと、`val binding: ~`の部分は`super.onCreate(savedInstanceState)`の下にあったほうがわかりやすいので、移動も頼みます

2019-09-10 05:19 UTC, t-fuji109 commented
修正が遅くなり、すみません
修正箇所直しました！よろしくお願いします

2019-09-12 08:16 UTC, shiita0903 approved these changes
:+1:

2019-09-12 08:16 UTC, merged