[WIP]
ann-kensaku/ToDoRank-Android pull request #6
Opened 2019-09-18 02:46 UTC by t-fuji109

2019-09-19 17:20 UTC, shiita0903 requested changes

2019-09-19 17:20 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +@Database(entities = [Item::class], version = 2)
versionは1からにしよう。
versionを上げるタイミングはリリースしたあとに、マイグレーションが必要なタイミングなので、しばらくは1のままで大丈夫

2019-09-19 17:20 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/Item.kt
> +    var title: String? = null
titleが無いことは今の所想定してないのでNullableにしなくても良さそう

2019-09-20 00:34 UTC, t-fuji109 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +@Database(entities = [Item::class], version = 2)
わかりました
修正しておきます

2019-09-25 13:47 UTC, t-fuji109 commented
名前変更しました
よろしくお願いします

2019-09-26 17:55 UTC, shiita0903 requested changes
コルーチンとか使ってて素晴らしい！！
幾つかコメントしたので修正お願いします

2019-09-26 17:55 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +                    val todoDao = todoDatabase.todoDao()
データ保存できるようになったし、サンプル挿入はもうやらなくていいと思う。
deleteAll()もしないようにして、アプリを閉じてもデータが保存されていることを確認できるようにしよう。
あとcoroutineScopeをインスタンスで渡すことはあんまりやらないかな。スコープが定義されているところでsuspend functionを呼ぶ方が良い。

2019-09-26 17:55 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/RecyclerAdapter.kt
> +    private val todoViewModel: TodoViewModel,
ViewModelのインスタンスを渡すよりは`onClick`みたいに関数リテラルのコールバック渡したほうが良いかな

2019-09-27 02:41 UTC, t-fuji109 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +                    val todoDao = todoDatabase.todoDao()
ありがとうございます！
coroutineScopeのあたりが十分に分かっていないのですが、インスタンスで渡すことはあまりないというのはTodoDatabaseCallbackに渡しているところでしょうか

2019-09-27 16:23 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +                    val todoDao = todoDatabase.todoDao()
そうそう。けどこの例だとsuspend functionに出来ないな…。
今回の使用用途だとサンプルデータの挿入で、キャンセルが必要無くて完了待てたほうが良いから、runBlockingとか使っちゃって良いかと思う。

2019-09-27 16:24 UTC, shiita0903 commented on app/src/main/java/jp/ann/kensaku/todorank/TodoDatabase.kt
> +                    val todoDao = todoDatabase.todoDao()
サンプル挿入削除したからメソッドの仮引数のscopeも削除しよう

2019-10-01 11:39 UTC, t-fuji109 commented
修正加えてみました
サンプルデータの挿入のところを除くと、scope.launch()自体が使われなくなり、runBlockingも使わなかったのですが、違う修正方法があるのでしょうか

2019-10-10 07:05 UTC, shiita0903 approved these changes

2019-10-10 07:08 UTC, shiita0903 commented
> 修正加えてみました
> サンプルデータの挿入のところを除くと、scope.launch()自体が使われなくなり、runBlockingも使わなかったのですが、違う修正方法があるのでしょうか
> よろしくお願いします

サンプルデータの挿入をもし残すなら`scope.launch`の部分を`runBlocking`で置き換えられるって話．なので消した今は特に気にしなくて大丈夫だよ．

2019-10-10 07:09 UTC, merged